name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-04-09"
keep_vars = true

[observability]
enabled = true

#[[d1_databases]]
#binding = "db"			#d1数据库绑定名默认不可修改
#database_name = ""		#d1数据库名字
#database_id = ""		#d1数据库id

#[[kv_namespaces]]
#binding = "kv"			#kv绑定名默认不可修改
#id = ""					#kv数据库id

#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = ""		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "83f73f7c-e9b6-4de2-bdec-bab0d5f0fdcb"

[[kv_namespaces]]
binding = "kv"
id = "99ba89c9ec0e404a8def3a200256c947"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail-attachments"

[assets]
binding = "assets"
directory = "./dist"

[vars]
orm_log = false
domain = ["peticao5005.pt"]
admin = "contacto@peticao5005.pt"
