name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-04-09"
keep_vars = true

[observability]
enabled = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "83f73f7c-e9b6-4de2-bdec-bab0d5f0fdcb"

[[kv_namespaces]]
binding = "kv"
id = "99ba89c9ec0e404a8def3a200256c947"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail-attachments"

[assets]
binding = "assets"
directory = "./dist"
